# APT Detection System Configuration

model_paths:
  base_dir: models/
  lightgbm: lightgbm_model.pkl
  bilstm: bilstm_model.h5

training_params:
  lightgbm:
    num_leaves: 31
    learning_rate: 0.05
    n_estimators: 100

  bilstm:
    epochs: 5
    batch_size: 32
    lstm_units: 64

split_params:
  test_size: 0.2
  random_state: 42

data_paths:
  dataset: synthetic_apt_dataset.csv

# Data source connectors configuration
data_sources:
  # Wazuh EDR connector configuration
  wazuh:
    enabled: false  # Set to true to enable Wazuh integration
    api_url: "https://wazuh.example.com:55000"
    username: "wazuh-api-user"
    password: "wazuh-api-password"
    verify_ssl: false
    fetch_interval: 60  # Seconds between fetches

  # Elasticsearch SIEM connector configuration
  elasticsearch:
    enabled: false  # Set to true to enable Elasticsearch integration
    hosts: ["localhost:9200"]
    index_pattern: "winlogbeat-*"
    username: "elastic"
    password: "changeme"
    verify_certs: false
    fetch_interval: 60  # Seconds between fetches

kafka:
  bootstrap_servers: localhost:9092
  topic: apt_topic

dashboard:
  host: 127.0.0.1
  port: 5000
  debug: true

settings:
  overwrite_models: true
  log_level: INFO
  # Data collection settings
  collection_interval_seconds: 60  # How often to collect data from connectors
  # Behavioral analytics settings
  behavioral_analytics:
    baseline_period_days: 7    # Days of data to use for baseline
    anomaly_threshold: 0.8     # Threshold for anomaly detection (0.0-1.0)
    time_window_minutes: 10    # Time window for feature aggregation
  # Alert settings
  alerts:
    max_alerts: 1000           # Maximum number of alerts to store in memory
    retention_days: 30         # How long to keep alerts (for database implementation)
